### ISSUE TITLE
Visualise the pan & rotation

### ISSUE THREAD

**Issue by morgz** [itchingpixels/talks#1]
Hey Mark - Thanks for this example! I found it on Natasha's Swift email. I forked and added a draggable and rotatable view as I wanted to see it happen. You can get the code here: https://github.com/morgz/talks/commit/6df1f338c1de7a2d865a4992f00f9dc14884edf8

I can do a pull request if you want, looks like a lot of changes because it's brought some Xcode guff and the indentation changed in the two view controllers but not much was actually added.

**Comment by almostintuitive** [comment]
cool thank you!

this is really useful, it's nice to visualize exactly what's going on - console logging is not really spectacular:)

it would be nice to merge this in, but I'd like to retain the original example, since that's what the blogpost presented - and it's nice to have a stripped down version of it, just because it's slightly easier to explain that one.

do you mind if I add it as a fourth class?

I also have some suggestions on how to improve it, I'll get back to you in a few hours!

cheers!

**Comment by almostintuitive** [comment]
second look, actually running it: ohh this is quite nice!

can I have a pull request?:)

**Comment by morgz** [comment]
Pull Request: #2

**Comment by almostintuitive** [comment]
thanks a lot!:)
